server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

security:
  jwt:
    secret-key: ${SECRET-KEY}